name: Test Action

on:
  push:
    branches: [master, main]

jobs:
  use-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fetch Angular routes to file
        uses: ./
        with:
          file: "testfile.txt"
          url: "https://api.jsonbin.io/v3/qs/65898bbfdc74654018888f7c"
          responsePath: "record"
          debug: "true"
      - name: List files
        run: ls
      - name: Check routes file content
        run: cat testfile.txt
